server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://176.124.216.223:5432/kafkaapp
    username: kafkaapp
    password: kafkaappkafkaapp
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"